### PR TITLE
Add GitHub Action

### PR DESCRIPTION
**Pull request by YadominJinta**
Add github action workflow to auto build.

### CODE REVIEW

**Comment by YadominJinta** [comment]
@zxystd Does it looks good to you?

**Comment by williambj1** [comment]
Thank you for your contribution, we're actually considering adding GitHub Release distribution in CI as well.
Could you imitate the one in HeliPort? https://github.com/OpenIntelWireless/HeliPort/blob/master/.github/workflows/main.yml

Also, AFAIK, GitHub Actions only provides SDKs for macosx10.15, users have complained about its compatibility so it's better to use 10.12, you could find an example in VoodooI2C's CI config file.

**Comment by YadominJinta** [comment]
@williambj1 Other versions of sdk can get from [phracker/MacOSX-SDKs]([https://github.com/phracker/MacOSX-SDKs)

**Comment by williambj1** [comment]
You could use this:
https://github.com/VoodooI2C/VoodooI2C/blob/451739ce4a736fa8afb591f73ef45f7fec240960/.circleci/config.yml#L25

**Comment by zxystd** [comment]
No any update for a few days. we are also doing CI/CD configuration. You can reopen this PR if you have any useful updates or ideas. thanks for your contribution.

**Pull request closed without merging**
